### ISSUE TITLE
Array parsing error and struggle to use read

### ISSUE THREAD

**Issue by dernate** [NothinRandom/pyopcxmlda#1]
I am struggeling with the output from the getProperties and read methods from the class Client. The method getStatus works and affirms an established connection to the opcxmlda server. Another tool can also access the server properly.

1. getProperties: I am able to extract and display the value of an item from the opc server as long as the item contains a single value such as an int. If the value of the server-item is an array, in my case an arrayofdoubles the value will not be displayed and the response is empty. The raw response contains the wanted information but it seems that it cannot be parsed and displayed.
2. read: With read on the other hand I can't seem to get any information from the server whatshowever and the payload shows: "Request Options pointer is NULL", even if I know there is a value that can be requested (e.g. can display it with getProperties)

Code for 1.: 
```
from pyopcxmlda import Client
from pyopcxmlda.tag import Tag

__HOST = "0.0.0.0" //exemplary
__PORT = 1234      //exemplary
__ITEMS = [
    Tag(itemName="Loc/Wec/Plant1/P")
]
with Client(host=__HOST, port=__PORT) as plc:
    response = plc.getProperties(itemList=__ITEMS)
    print(response)
```
`response = {list: 1}  [,Loc/Wec/Plant1/P,xsd:int,'1294',2023-11-02T09:48:23.707-01:00,readable,2310,good,noEnum,]`
As we can see: I can get the value 1294.

1.1 If I want to read an array value (change itemName="Loc/Wec/Plant1/Log/Wecstd/Month/Val-1")

If I look into the raw response (bytes): 

`b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://opcfoundation.org/webservices/XMLDA/1.0/" xmlns:ns2="Service"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body id="_0"><GetPropertiesResponse xmlns="http://opcfoundation.org/webservices/XMLDA/1.0/"><GetPropertiesResult xsi:type="ns1:ReplyBase" ServerState="running" RevisedLocaleID="en-us" ReplyTime="2023-11-02T12:55:21.546+00:00" RcvTime="2023-11-02T12:55:21.546+00:00"></GetPropertiesResult><PropertyLists xsi:type="ns1:PropertyReplyList" ItemName="Loc/Wec/Plant1/Log/Wecstd/Month/Val-1" ItemPath=""><Properties xsi:type="ns1:ItemProperty" Description="Item access rights" Name="ns1:accessRights" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="xsd:string">readable</Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Item canonical data type" Name="ns1:dataType" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="xsd:QName">ArrayOfDouble</Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Item EU type" Name="ns1:euType" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="xsd:string">noEnum</Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Item quality" Name="ns1:quality" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="ns1:OPCQuality" VendorField="0" LimitField="none" QualityField="good"></Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Fastest rate (in milliseconds) at which the server could obtain data from the underlying data source" Name="ns1:scanRate" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="xsd:float">0</Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Item timestamp" Name="ns1:timestamp" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="xsd:dateTime">2023-10-30T22:00:00.000-01:00</Value></Properties><Properties xsi:type="ns1:ItemProperty" Description="Item value" Name="ns1:value" ItemName="Val-1" ItemPath="Loc/Wec/Plant1/Log/Wecstd/Month/"><Value xsi:type="ns1:ArrayOfDouble"><double>44165</double><double>7.9000000000000004</double><double>22.199999999999999</double><double>14.17</double><double>20.079999999999998</double><double>972</double><double>2448</double><double>720</double><double>715908</double><double>1</double><double>43</double><double>322</double><double>-542</double><double>971</double><double>971</double><double>970</double><double>971</double></Value></Properties></PropertyLists></GetPropertiesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>'`

you can see the values with correct types (e.g. <double>44165</double>) but after parsing the response is empty: response = {list: 0} [].

2.  The problem I have with read is that if I use the same code but with read instead of getProperties the response is empty regardless what value is in the item (int or array) and the raw payload (bytes) shows "Request Options pointer is NULL"

Code for 2.:

```
from pyopcxmlda import Client
from pyopcxmlda.tag import Tag

__HOST = "0.0.0.0" //exemplary
__PORT = 1234       //exemplary
__ITEMS = [
    Tag(itemName="Loc/Wec/Plant1/P")
]
with Client(host=__HOST, port=__PORT) as plc:
    response = plc.read(itemList=__ITEMS)
    print(response)
```

`response = {list: 0} []`

raw payload (str):

`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://opcfoundation.org/webservices/XMLDA/1.0/"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body><ns0:Read><ns0:ItemList><ns0:Items ItemPath="" ItemName="Loc/Wec/Plant1/P" ClientItemHandle="Loc/Wec/Plant1/P" ></ns0:Items></ns0:ItemList></ns0:Read></SOAP-ENV:Body></SOAP-ENV:Envelope>`

raw response (bytes):

`b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://opcfoundation.org/webservices/XMLDA/1.0/" xmlns:ns2="Service"><SOAP-ENV:Header></SOAP-ENV:Header><SOAP-ENV:Body id="_0"><SOAP-ENV:Fault><faultcode>LiXMO Read:</faultcode><faultstring>The Request Options pointer is NULL</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>'`

For me it seems like a problem with correctly creating the payload and parsing the response. Can you help me to figure it out? 
Thanks!

**Comment by dernate** [comment]
I found that the values i want to get from the opc server get picked up from the p object (line 324 in pyopcxmlda/client.py) captures all values one by one as it should but properties cant get the values. It seems that the elif function (line 337) uses value=value.text and this doesnt go deep enough into the xml so it can't see what is in the array and therefore ignores it.

**Comment by NothinRandom** [comment]
@dernate,

Sorry for late response.  I wrote this, but forgot to hit the Comment button.... anyway...  If you think that you have figured out a solution, please feel free to PR.

Yes, I can take a look at this.  Could you do me a favor and enable logging and send me the output?  If it contains "sensitive" information that you can't freely share to a wide audience, maybe send directly to my email instead.

Thanks,

**Comment by dernate** [comment]
I can send you the output.log that I got from enabling logging in your Client.py. In output(getProperties).log and output(read).log: the first entry is about the array and the second one is about the single value (e.g. int).
[output(getProperties).log](https://github.com/NothinRandom/pyopcxmlda/files/13268842/output.getProperties.log)
[output(read).log](https://github.com/NothinRandom/pyopcxmlda/files/13268844/output.read.log)
Hope this helps, if you need any further information you can message me.

**Comment by NothinRandom** [comment]
Depending on how the server is implemented, it could be finicky.  Looking at the provided logs, it could be because of empty `ItemPath`, incorrect namespace, etc.  Could you try a quick test and specify these parameters for read?  

`ItemPath` as `Loc/Wec/Plant1/Log/Wecstd/Month/`

`ItemName` as `Val-1`

**Comment by dernate** [comment]
So for `read` I tried changing the `itemName` to be the item e.g. `Val-2` that contains the data and the `itemPath` to the path that contains the item: `Loc/Wec/Plant1/Log/Wecstd/Month` but it doesn't seem to make a difference.
[output(getProperties).log](https://github.com/NothinRandom/pyopcxmlda/files/13279532/output.getProperties.log)
[output(read).log](https://github.com/NothinRandom/pyopcxmlda/files/13279533/output.read.log)

**Comment by NothinRandom** [comment]
Could you send a message to my email?  Let's figure this out offline since we might need to do a live call for troubleshooting.  Once we resolve, I'll update code base and resolve issue.

**Comment by dernate** [comment]
Hey, sorry but I don't see an email on your profile. Sorry for mixing up two problems: First the "GetProperties" challenges and then the "Read" errors. I'm trying to solve it myself, I'll keep you updated.

**Comment by dernate** [comment]
I fixed the problems with the read method and created a pull request.
